### ISSUE TITLE
Cannot to install in HydrogenOS 11

### ISSUE THREAD

**Issue by JackA1ltman** [MaterialCleaner/Media-Provider-Manager#11]
![Screenshot_20221022-110719.jpg](https://user-images.githubusercontent.com/82563979/197316418-6116fd59-b750-4cd5-b481-50e7b180bbcd.jpg)
Only can installed the alpha5.but the alpha5 i gave the lsposed permission but still tell me need it

**Comment by GuhDoy** [comment]
Oops, it's my mistake. The apk is not signed. I have re-uploaded the apk, please download again.
