### ISSUE TITLE
MIUI无法拦截下载管理程序写入

### ISSUE THREAD

**Issue by JadeButterfly** [MaterialCleaner/Media-Provider-Manager#14]
启用"实验"提供的拦截下载管理程序模板(应用到媒体存储设备，MTP主机和下载管理程序)后执行实验一的结果为:
使用记录均显示为插入被拦截。
此应用图片页面看不到图片，但是文件夹里已写入图片。

通过您开发的MaterialCleaner的文件系统记录功能查询到"媒体存储设备"打开图片的操作。
测试平台为Redmi Note11T Pro,MIUI 13.0.11

**Comment by GuhDoy** [comment]
这是预期行为

**Comment by Vstory** [comment]
> 这是预期行为

正常难道不是该拦截成功吗？

**Comment by GuhDoy** [comment]
@Vstory 请查看实验中的说明“只能拦截媒体存储对媒体文件的记录，而无法阻止保存文件”。
