### ISSUE TITLE
LSPosed激活模块

### ISSUE THREAD

**Issue by Webpage-gh** [MaterialCleaner/Media-Provider-Manager#17]
请问怎么激活这个模块？我在LSP勾选了下载管理程序（com.android.providers.downloads）和系统框架并且重启手机，仍然使用不了。我的系统是MIUI Global 13.0.7稳定版

**Comment by GuhDoy** [comment]
请提供lsp日志

**Comment by Webpage-gh** [comment]
这是详细日志2023年3月25日 下午4:56，GuhDoy ***@***.***>写道：
请提供lsp日志

**Comment by Webpage-gh** [comment]
[这](https://github.com/Webpage-gh/Redirect/raw/gh-pages/LSPosed_2023-03-25T17_48_29.525028.zip)是这份日志的下载链接

**Comment by GuhDoy** [comment]
没发现 MPM 的报错

**Comment by Webpage-gh** [comment]
请问有其他方法吗，这个模块应该有很大作用，我想试试
![Screenshot_2023-03-26-22-18-47-362_bin mt plus](https://user-images.githubusercontent.com/70434775/227781984-c9aaa373-ccf0-41bc-af11-3caa8790e86f.jpg)

**Comment by GuhDoy** [comment]
![Screenshot_2023-03-27-19-01-42-992_bin.mt.plus.jpg](https://user-images.githubusercontent.com/46047320/227923685-7770e98a-3202-4fe8-9d9b-c2defcc8c16a.jpg)

你这个日志里有个问题，系统服务全炸了，这个得靠你自己排查是什么东西导致的。
