### ISSUE TITLE
部分应用打开相册图片数量出错

### ISSUE THREAD

**Issue by z134git** [MaterialCleaner/Media-Provider-Manager#18]
反复尝试后发现
若不先使用nomedia隐藏目标文件夹，直接在模板中过滤路径，会导致某些应用（公司内部的垃圾应用）读取相册内的图片数量出错，始终无法显示最新的图片。
例如camera相册2000张，Twitter相册200张。直接对应用过滤Twitter后，会导致在应用中camera只显示1800张。先隐藏Twitter打开一次应用，再过滤就没问题，此后再解除隐藏，也不会产生影响。

垃圾应用肯定有问题，因为微信什么的没有这种特性。但是我想模块这边也能查查看有没有什么办法？

还有就是想问问能不能做个白名单模式啊大佬🥰

**Comment by GuhDoy** [comment]
没有办法
