### ISSUE TITLE
关于添加模板应用黑名单的功能建议

### ISSUE THREAD

**Issue by YXuuan** [MaterialCleaner/Media-Provider-Manager#19]
模板应用到的应用能否实现黑名单制，使应用在只要部分应用不需要过滤这些路径的情况下更好作用。

**Comment by GuhDoy** [comment]
现在就是黑名单制

**Comment by YXuuan** [comment]
对路径是黑名单制（勾选的应用禁止访问指定路径），但能否实现对应用黑名单制（只允许勾选的应用访问指定路径）？

**Comment by GuhDoy** [comment]
你说的好像叫白名单

**Comment by YXuuan** [comment]
好的，是的，请问能否实现呀。就实现类似有指定范围作用的.nomedia了。

**Comment by GuhDoy** [comment]
我不需要所以不考虑，你如果非常需要就自己做吧。
