### ISSUE TITLE
通过媒体存储插入文件的问题

### ISSUE THREAD

**Issue by Vstory** [MaterialCleaner/Media-Provider-Manager#20]
![Screenshot_2023-08-31-20-50-31-480_me gm cleaner plugin](https://github.com/MaterialCleaner/Media-Provider-Manager/assets/20795557/0ec3d3a4-c8e0-475f-87bd-47ba276f1b4e)

如图所示，类似这样的文件我该如何选择？
拦截能不能支持自定义拦截文件

**Comment by GuhDoy** [comment]
这不是通过媒体存储插入，因此你无法拦截，实验中有相关说明。
据我所知，这是MIUI Daemon创建的，如果有需要请使用Cleaner的存储重定向功能解决。

**Comment by Vstory** [comment]
> 这不是通过媒体存储插入，因此你无法拦截，实验中有相关说明。 据我所知，这是MIUI Daemon创建的，如果有需要请使用Cleaner的存储重定向功能解决。

好的，谢谢
