### ISSUE TITLE
Force close on usage record because of db row too big

### ISSUE THREAD

**Issue by moon-cacke** [MaterialCleaner/Media-Provider-Manager#5]
Thanks for your work...

![Screenshot_20220521-011238_MatLog_Libre](https://user-images.githubusercontent.com/105121763/169623645-ad3e2316-718d-47b1-9e02-b0ad3c05e2f2.png)

**Comment by GuhDoy** [comment]
I'll try to fix this on the next release (alpha4), but I can't promise an elegant way to solve it.

Can you estimate how many paths the record with the error contains? This might help fix the problem.

**Comment by moon-cacke** [comment]
@GuhDoy thanks... here is the data cell on row 19 from the database
```
["/storage/emulated/0/Movies/Capture/fvideoshiom_2b544927d008afedd6700d40080556a0.mp4","/storage/emulated/0/Movies/Capture/fvideoshiom_e40bf2ba588d4f4600068e448831247a.mp4","/storage/emulated/0/Movies/Capture/fvideoshiom_0f6c8443017701c30482b977e81399da.mp4","/storage/emulated/0/Movies/Capture/recorded analytics of schematics of the particles accelerator at the labs f014739.mp4","/storage/emulated/0/Movies/Capture/fvideoshiom_1461393efde5616192888cafe637b949.flv"]�
```

**Comment by GuhDoy** [comment]
Um...It doesn't look like a lot of data? Can you upload the database file? I'll see if I can reproduce the problem.

**Comment by moon-cacke** [comment]
at some point this seems to be solved in the alpha3... was having this issue on alpha1... the old db still makes the app alpha3 to FC... but when deleting the db and simulating access to the problematic files locations it does not cause problems any more... may be the old versions recorded datas that it should not put in a single cell...

It would be usefull to add a feature to set a max size for the db... mine reched 1gb in a month
