### ISSUE TITLE
在Xposed框架中激活模块并重启系统才能使用此功能

### ISSUE THREAD

**Issue by bantouguo** [MaterialCleaner/Media-Provider-Manager#6]
安卓12，安装好媒体存储设备管理APP（alph4）后，打开后提示“在Xposed框架中激活模块并重启系统才能使用此功能”，我在打开lsposed，打开模块，进入后点击启用模块，  勾选了下载管理程序和系统框架及各种用户APP，然后重启，进系统后，发现打开媒体存储设备管理APP，还是会显示“在Xposed框架中激活模块并重启系统才能使用此功能”，我不知道哪里出了问题，您能告诉我么，谢谢

**Comment by Mubai-meng** [comment]
一样的问题，你解决了吗

**Comment by bantouguo** [comment]
没有啊，我还卸载了，然后安装了一下alph3版本，发现还是会发生同样的问题，我的手机是红米note11tpro，刷的国际板miui13，安卓12，看作者什么时候能回复一下吧

**Comment by bantouguo** [comment]
> 一样的问题，你解决了吗

没有啊，我还卸载了，然后安装了一下alph3版本，发现还是会发生同样的问题，我的手机是红米note11tpro，刷的国际板miui13，安卓12，看作者什么时候能回复一下吧

**Comment by GuhDoy** [comment]
是否勾选了 媒体存储设备？
如果是，发一下 lsposed 日志

**Comment by bantouguo** [comment]
[Uploading LSPosed_2022-08-31T11_15_47.647.zip…]()

**Comment by bantouguo** [comment]
之前没有勾选媒体存储设备，勾选后重启还是同样的问题，我不知道我导出的日志对不对，您看看，不对我再导出一遍

**Comment by bantouguo** [comment]
> 是否勾选了 媒体存储设备？ 如果是，发一下 lsposed 日志

[LSPosed_2022-08-31T11_15_47.647.zip](https://github.com/MaterialCleaner/Media-Provider-Manager/files/9458381/LSPosed_2022-08-31T11_15_47.647.zip)

**Comment by bantouguo** [comment]
[Uploading LSPosed_2022-08-31T11_15_47.647.zip…]()

**Comment by GuhDoy** [comment]
你的系统服务为什么全炸了
关掉其它模块试试？

```
[ 2022-08-31T11:12:08.873        0:   770:  1495 W/LSPosedService  ] pm is dead
[ 2022-08-31T11:12:08.874        0:   770:  1495 W/LSPosedService  ] am is dead
[ 2022-08-31T11:12:08.874        0:   770:  1495 I/LSPosedService  ] service activity is dead. 
[ 2022-08-31T11:12:08.874        0:   770:  1495 I/LSPosedService  ] clear ServiceManager
[ 2022-08-31T11:12:08.874        0:   770:  1495 W/LSPosedService  ] system server died
[ 2022-08-31T11:12:08.875        0:   770:  1494 W/LSPosedService  ] um is dead
[ 2022-08-31T11:12:08.883        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2022-08-31T11:12:09.884        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2022-08-31T11:12:10.885        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.

Logd maybe crashed (err=No such file or directory), retrying in 1s...
```

**Comment by bantouguo** [comment]
> 你的系统服务为什么全炸了 关掉其它模块试试？
> 
> ```
> [ 2022-08-31T11:12:08.873        0:   770:  1495 W/LSPosedService  ] pm is dead
> [ 2022-08-31T11:12:08.874        0:   770:  1495 W/LSPosedService  ] am is dead
> [ 2022-08-31T11:12:08.874        0:   770:  1495 I/LSPosedService  ] service activity is dead. 
> [ 2022-08-31T11:12:08.874        0:   770:  1495 I/LSPosedService  ] clear ServiceManager
> [ 2022-08-31T11:12:08.874        0:   770:  1495 W/LSPosedService  ] system server died
> [ 2022-08-31T11:12:08.875        0:   770:  1494 W/LSPosedService  ] um is dead
> [ 2022-08-31T11:12:08.883        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.
> [ 2022-08-31T11:12:09.884        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.
> [ 2022-08-31T11:12:10.885        0:   770:   770 I/LSPosedService  ] service activity is not started, wait 1s.
> 
> Logd maybe crashed (err=No such file or directory), retrying in 1s...
> ```

你好，我重启了几次，看了看那个日志，发现服务还全都是炸的，我也不清楚什么原因，但是其他的lsposed模块都能正常运行，只有媒体存储设备管理不行。
最后我用了一个终极的方法，重新刷机，不再使用国际版系统，刷了一个别人制作的miui国行精简系统，媒体存储设备管理就能够正常运行了！
