### ISSUE TITLE
Wheres the GUI?

### ISSUE THREAD

**Issue by stylemessiah** [MaterialCleaner/Media-Provider-Manager#8]
Installed (Android 12 running Lsposed(Zygisk)) and module activated, but wheres the management GUI as in the README picture? All i get is a generic launcher icon that shows the About page .....

**Comment by GuhDoy** [comment]
Settings -> Template management -> Create template

or

App Management -> any app -> Create template

**Comment by GuhDoy** [comment]
Switch pages with the sidebar.

**Comment by stylemessiah** [comment]
Ahh, i didnt notice the menu....

If it were me developing it, id have the app land on anything BUT the About
page....would have avoided this confusion for one thing :)
