### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by bantouguo** [MaterialCleaner/Media-Provider-Manager#9]
你好开发者，首先感谢你设计的软件，媒体存储设备再也不无限膨胀了~~

我有一个安装上的问题想了解一下，我的情况是红米note11tpro，andorid12，miui13  magisk25.2，lsposed

安装了您软件的时候，系统提示软件所需要的权限，其中有两个权限，拥有完全的网络访问权限、查看网络连接（见附件）

但我看您软件介绍中说只需要下面这一个权限，我不知道为什么我的系统会这么提示，谢谢~

Media file manager (no root or Xposed needed, only requires [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE) permission)

![微信图片_20220927143649](https://user-images.githubusercontent.com/112363773/192454532-f66cb17b-9310-4e9a-b2a6-bf5cd0d6b285.jpg)
![微信图片_202209271436491](https://user-images.githubusercontent.com/112363773/192454539-77994302-07a6-428f-88d5-1f9f2f03fa75.jpg)

**Comment by GuhDoy** [comment]
介绍中说的是媒体文件浏览器功能只需要读取外部存储空间权限，不是指应用。
